### ISSUE TITLE
boot FMCB from slot 2

### ISSUE THREAD

**Issue by eadmaster** [israpps/FreeMcBoot-Installer#12]
sorry if this is not the right place to ask,
it is possible to load FMCB from the slot 2 instead of 1?

similar to this:
https://github.com/brad-lin/FreePSXBoot/issues/55

**Comment by israpps** [comment]
Yes, it is possible!

FreeMcBoot pretends to be a console system update.

The console looks for those on both slots!

So yeah, your FreeMcBoot KELF will be loaded from seccond port as long as the console didnt find any valid KELF on the first slot
