### ISSUE TITLE
no apps 1953

### ISSUE THREAD

**Issue by Mdv00** [israpps/FreeMcBoot-Installer#15]
i installed fmcb 1953 and there is only one app, opl and nothing else.

**Comment by israpps** [comment]
Hi!
Did you manipulate the contents of the `INSTALL` folder?

**Comment by Mdv00** [comment]
no, in the apps folder there is only opl. i checked the other versions and its the same

**Comment by israpps** [comment]
> no, in the apps folder there is only opl. i checked the other versions and its the same

Only OPL is pasted by default on `APPS`

wLaunchELF is placed on `mc?:/BOOT/BOOT.ELF`

**Comment by Mdv00** [comment]
i thought they were newbie packs, you listed the app contents but its not there or do i need to my own apps like esr?

**Comment by israpps** [comment]
> i thought they were newbie packs, you listed the app contents but its not there or do i need to my own apps like esr?

It is on a extra package, ready to be placed on usb or HDD

**Comment by israpps** [comment]
https://github.com/israpps/FreeMcBoot-Installer/releases/tag/APPS

**Comment by Mdv00** [comment]
i have a problem with esr, it won't boot from the menu, it will only boot if i manually select the elf file.
i have it in the apps folder, does it need to go in the boot folder?

**Comment by israpps** [comment]
> i have a problem with esr, it won't boot from the menu, it will only boot if i manually select the elf file. i have it in the apps folder, does it need to go in the boot folder?

Maybe you sould add the path on the ESR path configuration of FreeMcBoot

**Comment by Mdv00** [comment]
i have found the problem why esr would not boot from the menu, it won't work with clone cards only official cards. it might be something to do with magic gate.
is there a fix for clone cards?

**Comment by israpps** [comment]
I don't think ESR depends on magicgate...

**Comment by Mdv00** [comment]
with an official card games boot automatically, with a clone card they won't boot, just a black screen

**Comment by israpps** [comment]
Closing this since it because an issue with esr at the end
