### ISSUE TITLE
Can't see USB in Free McBoot Configurator

### ISSUE THREAD

**Issue by skelletR** [israpps/FreeMcBoot-Installer#21]
Best work. I connect a usb exfat, and i go to Free McBoot Configurator after in configure OSDSYS options and Configure Item to add a manual elf file but when go to path1 to add the elf file from mass the mass is empty why? I have installed in memory card the FMCBInstaller _EXFAT.elf

**Comment by israpps** [comment]
> Best work. I connect a usb exfat, and i go to Free McBoot Configurator after in configure OSDSYS options and Configure Item to add a manual elf file but when go to path1 to add the elf file from mass the mass is empty why? I have installed in memory card the FMCBInstaller _EXFAT.elf

FreeMcBoot and it's configurator are totally incompatible with exfat usb devices. and there is nothing we can do to make them use exfat drivers. because they load only two USB drivers from memory card. to make them use EXFAT USB they have to load at least 4 (USB, BDM, and two modules that come with BDM)

Therefore, we can't do it. because FreeMcBoot 1.9xx is closed source.

If you are looking for a bootloader wich can access and run apps from EXFAT usb you can try my own bootloader, PS2BBL

**Comment by skelletR** [comment]
> > Best work. I connect a usb exfat, and i go to Free McBoot Configurator after in configure OSDSYS options and Configure Item to add a manual elf file but when go to path1 to add the elf file from mass the mass is empty why? I have installed in memory card the FMCBInstaller _EXFAT.elf
> 
> FreeMcBoot and it's configurator are totally incompatible with exfat usb devices. and there is nothing we can do to make them use exfat drivers. because they load only two USB drivers from memory card. to make them use EXFAT USB they have to load at least 4 (USB, BDM, and two modules that come with BDM)
> 
> Therefore, we can't do it. because FreeMcBoot 1.9xx is closed source.
> 
> If you are looking for a bootloader wich can access and run apps from EXFAT usb you can try my own bootloader, PS2BBL

oh, understand, thanks for answer, because yesterday i found your cheat engine with exfat support, i go to download, thanks again

**Comment by israpps** [comment]
> > > Best work. I connect a usb exfat, and i go to Free McBoot Configurator after in configure OSDSYS options and Configure Item to add a manual elf file but when go to path1 to add the elf file from mass the mass is empty why? I have installed in memory card the FMCBInstaller _EXFAT.elf
> > 
> > 
> > FreeMcBoot and it's configurator are totally incompatible with exfat usb devices. and there is nothing we can do to make them use exfat drivers. because they load only two USB drivers from memory card. to make them use EXFAT USB they have to load at least 4 (USB, BDM, and two modules that come with BDM)
> > Therefore, we can't do it. because FreeMcBoot 1.9xx is closed source.
> > If you are looking for a bootloader wich can access and run apps from EXFAT usb you can try my own bootloader, PS2BBL
> 
> oh, understand, thanks for answer, because yesterday i found your cheat engine with exfat support, i go to download, thanks again

[PS2BBL with installer](https://github.com/israpps/KELFBinder/releases/download/latest/KELFBinder.7z)

**Comment by skelletR** [comment]
> > > > Best work. I connect a usb exfat, and i go to Free McBoot Configurator after in configure OSDSYS options and Configure Item to add a manual elf file but when go to path1 to add the elf file from mass the mass is empty why? I have installed in memory card the FMCBInstaller _EXFAT.elf
> > > 
> > > 
> > > FreeMcBoot and it's configurator are totally incompatible with exfat usb devices. and there is nothing we can do to make them use exfat drivers. because they load only two USB drivers from memory card. to make them use EXFAT USB they have to load at least 4 (USB, BDM, and two modules that come with BDM)
> > > Therefore, we can't do it. because FreeMcBoot 1.9xx is closed source.
> > > If you are looking for a bootloader wich can access and run apps from EXFAT usb you can try my own bootloader, PS2BBL
> > 
> > 
> > oh, understand, thanks for answer, because yesterday i found your cheat engine with exfat support, i go to download, thanks again
> 
> [PS2BBL with installer](https://github.com/israpps/KELFBinder/releases/download/latest/KELFBinder.7z)

Thanks you, i have send you a message via email, if you can make work with exfat one program

**Comment by VisionR1** [comment]
@israpps Hi, i read some change and support now EXFAT FreeMcBoot and it's configurator?
