### ISSUE TITLE
Fmcb 1966 bug

### ISSUE THREAD

**Issue by Helxgamer** [israpps/FreeMcBoot-Installer#22]
Hello budy, how are you ?
I need help I installed fmcb 1966 but the apps do not open it stays on a black screen, whether opl or ulaunchelf, my ps2 is model 7500010, but in version 1965 it worked normally, can you tell if this incompatibility really exists or is it possible fix in newer version?

**Comment by israpps** [comment]
> Hello budy, how are you ? I need help I installed fmcb 1966 but the apps do not open it stays on a black screen, whether opl or ulaunchelf, my ps2 is model 7500010, but in version 1965 it worked normally, can you tell if this incompatibility really exists or is it possible fix in newer version?

is is a memory conflict...

because your console has a modchip installed

**Comment by Helxgamer** [comment]
Understand, well 1965 is my numbe of look ,thanks
