### ISSUE TITLE
Feature Requests sub-folders

### ISSUE THREAD

**Issue by VisionR1** [israpps/FreeMcBoot-Installer#30]
I hope I am as clear as possible

Is possible to add it sub-folders in front page ? For ps1 games if add it one by one front is lot space but if had a named folder for ps1 and after open it and show me games inside (i have a folder named ps2 and is boot the opl) but for popstarter not have this options only add one by one the elf file, if had it sub-folder more easy, open and after show the Xx.game.elf

**Comment by israpps** [comment]
FreeMcBoot is closed source, we cant easily modify it.



Just wait for this to be finished:

https://github.com/israpps/FreeMcBoot-Installer/assets/57065102/25e1d383-7e7f-4654-b988-df483ff59524

**Comment by VisionR1** [comment]
> FreeMcBoot is closed source, we cant easily modify it.
> 
> Just wait for this to be finished:
> 
>  POPSLDR_2.mp4

Yeah you tell me about that, just ask maybe bypass like your BDMAssault, something like that
i can't see the video

**Comment by israpps** [comment]
> New POPStarter, when release?

POPStarter launcher. I don't have the knowledge to make another POPStarter

**Comment by VisionR1** [comment]
> > New POPStarter, when release?
> 
> POPStarter launcher. I don't have the knowledge to make another POPStarter

Understand, i can't find it, only have xx.game.elf to launch the ps1 from wLaunchELF
