### ISSUE TITLE
[ISSUE]: SCPH-10000 startup problem

### ISSUE THREAD

**Issue by inaji6** [israpps/FreeMcBoot-Installer#38]
### Checks

- [X] I have checked [__existing issues__](https://github.com/israpps/FreeMcBoot-Installer/issues) for duplicates and found none
- [ ] I am using a build downloaded from [this repository](https://israpps.github.io/FreeMcBoot-Installer/test/8_Downloads.html)

### Describe the issue

I installed FMCB using ”FMCBinst-1966-[2024-10-01].7z".
After the FreeMCBoot logo appears, the screen remains black and no OSD appears.
I think it's a bug because "READ ME.TXT" says *The "Early Japanese"/PCMCIA units (SCPH-10000, SCPH-15000 and SCPH-18000) are fully supported.
Please fix it.

### Console model

SCPH-10000

### Where do you have the issue?

FreeMcBoot

### Program version (if possible, also provide hash seen on installer used)

1.966 2024-10-01 & 1.966 2024-07-01

**Comment by israpps** [comment]
closing. already answered
